get_filename_component(VTK_SMP_IMPLEMENTATION_HEADER_DIR ${VTK_SMP_CMAKE_IMPLEMENTATION_FILE} PATH)
include_directories(${VTK_SMP_IMPLEMENTATION_HEADER_DIR})

FIND_PACKAGE(Cilk REQUIRED)

IF(CILK_FOUND)
  message(STATUS "Cilk compiler found. Changing ${CMAKE_CXX_COMPILER} to ${CILK_COMPILER}")
  #set(CMAKE_CXX_COMPILER ${CILK_COMPILER} PARENT_SCOPE)
  set(CMAKE_CXX_FLAGS "-x c++ ${CMAKE_CXX_FLAGS}")
ELSE(CILK_FOUND)
  message(FATAL_ERROR "Cilk compiler not found.")
ENDIF(CILK_FOUND)

set(VTK_SMP_IMPLEMENTATION_LIBRARIES "")
