get_filename_component(VTK_SMP_IMPLEMENTATION_HEADER_DIR ${VTK_SMP_CMAKE_IMPLEMENTATION_FILE} PATH)
include_directories(${VTK_SMP_IMPLEMENTATION_HEADER_DIR})

FIND_PACKAGE(OpenMP REQUIRED)

set(VTK_SMP_IMPLEMENTATION_LIBRARIES)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
