vtk_module(vtkParallelSMP
  DEPENDS
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkCommonTransforms
    vtkFiltersCore
    vtkFiltersGeneral
    vtkParallelCore
  EXCLUDE_FROM_WRAPPING
  )
